### ISSUE TITLE
[iOS] XCode Archive : MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists

### ISSUE THREAD

**Issue by eTryp** [maplibre/maplibre-react-native#442]
Hi,

I'm using the latest version of the maplibre-react-native library (10.0.0-alpha.13) and I'm trying to create an archive on iOS to deliver a version via TestFlight. The debug version works well on iOS on a real device, but the last step, the archiving process, is failing with the following error:

```
“MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.
Domain: NSCocoaErrorDomain
Code: 516
Failure Reason: A file with the name “MapLibre.xcframework-ios.signature” already exists.
Recovery Suggestion: To save the file, either provide a different name, or move aside or delete the existing file, and try again.
```

I tried to downgrade the version on earlier 10.0.0-alpha.X but the issue is still present.

### Steps to Trigger Behavior

1. Add maplibre to the react-native project `yarn add @maplibre/maplibre-react-native`
2. Add podfile instruction https://github.com/maplibre/maplibre-react-native/blob/main/ios/install.md
3. Run pod install on ios folder
4. Build
5. Archive

Archive will failed with the error reported.

### Expected Behavior

Archive should be completed.

### Actual Behavior

Archive failed with the error MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists

### Version(s) affected

- Platform: iOS 
- OS version: 17.6.1
- Device type: iPhone 14 Pro Max
- Emulator/ Simulator: no
- Development OS: osx 14.6.1
- maplibre-react-native 10.0.0-alpha.13
- MapLibre GL version: 6.5.4
- React Native Version: 0.74.1

Thanks for your assistance and for your work.

**Comment by tyrauber** [comment]
hey @eTryp, this is a react-native app, not an expo app, correct? We ran into something like this with the expo config plugin. [This was the fix](https://github.com/maplibre/maplibre-react-native/pull/238/files).
```
 const shellScript = `if [ "$XCODE_VERSION_MAJOR" = "1500" ]; then
    echo "Remove signature files (Xcode 15 workaround)";
    rm -rf "$CONFIGURATION_BUILD_DIR/MapLibre.xcframework-ios.signature";
  fi`;
  ```

**Comment by eTryp** [comment]
Hi @tyrauber thank you for your feedback. Yes, it's a react-native bare app, not an expo app.

**Comment by lluisandreu** [comment]
Hi @tyrauber I am also facing this issue on maplibre-react-native 10.0.0-alpha.13 on iOS only when I archive the bundle. Is there a quick fix I could apply in order to archive the app?
Thanks.

**Comment by tyrauber** [comment]
Yep @lluisandreu, you need to add the shell script in the build phase.  Here is how to do it in xCode,
[xcode/running-custom-scripts-during-a-build](https://developer.apple.com/documentation/xcode/running-custom-scripts-during-a-build).  I am honestly not sure why the library is generating the signature or why that is necessary. It is something that popped up for a lot of libraries with xCode 15.

**Comment by markhaehnel** [comment]
I'm facing this exact issue with an expo app right now.

**Comment by tyrauber** [comment]
@markhaehnel, the expo config plugin should take care of this.  I think your issue might be related to xCode 16?  [It looks like we need to update](https://github.com/maplibre/maplibre-react-native/blob/main/plugin/src/withMapLibre.ts#L133-L136) the plugin to take account for the new version of xCode, as this problem persists.

````
  const shellScript = `if [ "$XCODE_VERSION_MAJOR" = "1500" ]; then
    echo "Remove signature files (Xcode 15 workaround)";
    rm -rf "$CONFIGURATION_BUILD_DIR/MapLibre.xcframework-ios.signature";
  fi`;
```

**Comment by markhaehnel** [comment]
> I think your issue might be related to xCode 16?
 I'm pretty sure it's XCode 16. Before i upgraded everything worked fine. Also on Expo Application Service (EAS) it works without any issues.

**Comment by tyrauber** [comment]
A fix is out in 10.0.0-alpha.14.  Disabled code signing of the library and updated the expo config plugin. Tested in the packages/expo-app example.  This should resolve the issue for both react-native and expo apps.  Please let us know otherwise. Thanks!

**Comment by madmeatballs** [comment]
> A fix is out in 10.0.0-alpha.14. Disabled code signing of the library and updated the expo config plugin. Tested in the packages/expo-app example. This should resolve the issue for both react-native and expo apps. Please let us know otherwise. Thanks!

it seems that updating to 10.0.0-alpha.14 doesn't solve the issue.

```
2024-09-19 09:15:03.611 xcodebuild[31746:1399763] Writing error result bundle to /var/folders/20/fw8097xd7wz030zfrnkzjr4r0000gn/T/ResultBundle_2024-19-09_09-15-0003.xcresult
xcodebuild: error: “MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.: The operation couldn’t be completed. File exists
```

**Comment by QuaduxIT** [comment]
Thank you all for the hard work and effort you’ve put into this library. I really appreciate being able to use it! 

Unfortunately, I'm still experiencing the same error in my Expo app.

```
▸ 2024-09-18 22:25:58.638 xcodebuild[3961:12639] Writing error result bundle to /var/folders/vn/nzbsghpn733f46w61_gbp33r0000gn/T/ResultBundle_2024-18-09_22-25-0058.xcresult

▸ xcodebuild: error: “MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.: The operation couldn’t be completed. File exists

2024-09-18 22:25:58.638 xcodebuild[3961:12639] Writing error result bundle to /var/folders/vn/nzbsghpn733f46w61_gbp33r0000gn/T/ResultBundle_2024-18-09_22-25-0058.xcresult

xcodebuild: error: “MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.: The operation couldn’t be completed. File exists

Exit status: 70

+---------------------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.220.0                 |

| sdk         | iPhoneOS17.5.sdk        |

+-------------+-------------------------+
```

**Comment by markhaehnel** [comment]
@madmeatballs @QuaduxIT Can you both try to remove your XCode DerivedData for that projects and do a `prebuild --clean` again?

For me it worked after these steps.

**Comment by tyrauber** [comment]
Thanks @markhaehnel, I was going to suggest the same thing. In the past, I have also deleted node_modules, ios and .expo directories manually, when running into to XCode build issues, but `prebuild --clean` should do it.   Were you able to submit a built to test flight?  Slightly concerned about the errors @madmeatballs reported.

**Comment by QuaduxIT** [comment]
I’m using eas build -p ios --profile development and don’t have an Apple device locally.
So there is no prebuild I can cleanup.
Android has no problem!

**Comment by tyrauber** [comment]
@QuaduxIT,  Did alpha.13 work for you?  

eas build just uses xcodebuild behind the scenes, so there is still xcode derived data  in your home directory, and while you may not need to run prebuild, eas build will run it for you and generate an ios directory with pod files and a build cache.

**Comment by markhaehnel** [comment]
> Thanks @markhaehnel, I was going to suggest the same thing. In the past, I have also deleted node_modules, ios and .expo directories manually, when running into to XCode build issues, but `prebuild --clean` should do it. Were you able to submit a built to test flight? Slightly concerned about the errors @madmeatballs reported.

Yes, i was able to submit to TestFlight with `eas build -e production -p ios --local` and then `eas submit`

**Comment by QuaduxIT** [comment]
@markhaehnel 
> Remote EAS builds also work for me.
    even without "ios" directory and no "prebuild --clean" ?

@tyrauber 
>Did alpha.13 work for you?
I'm surprised. Yes, with alpha.13 it is working.

I hope alpha.15 will work again for everybody !
thx for the quick help !

**Comment by tyrauber** [comment]
@QuaduxIT, if you are having this problem with Remote EAS builds, `eas build -e production -p ios` without the `--local` flag, it sounds like [EAS may be caching the dependencies](https://docs.expo.dev/build-reference/caching/#ios-dependencies).  Please try adding a cache key to eas.json, setting EAS_BUILD_DISABLE_COCOAPODS_CACHE, or cache Podfile.lock.

**Comment by madmeatballs** [comment]
> Thanks @markhaehnel, I was going to suggest the same thing. In the past, I have also deleted node_modules, ios and .expo directories manually, when running into to XCode build issues, but `prebuild --clean` should do it. Were you able to submit a built to test flight? Slightly concerned about the errors @madmeatballs reported.

still getting the same error when archiving for iOS

```
2024-09-19 15:39:44.805 xcodebuild[33506:2074978] Writing error result bundle to /var/folders/20/fw8097xd7wz030zfrnkzjr4r0000gn/T/ResultBundle_2024-19-09_15-39-0044.xcresult
xcodebuild: error: “MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.: The operation couldn’t be completed. File exists
```

I deleted node_modules, ios, and .expo directories manually, then running `prebuild --clean` for good measure. I also removed the XCode deriveddata for the project as mentioned by @markhaehnel.

The only way I am able to archive successfully was when adding the build phase script mentioned here https://github.com/maplibre/maplibre-react-native/issues/442#issuecomment-2357829852, but this gives me the warning I showed earlier but is successfully uploaded to testflight.

**Comment by QuaduxIT** [comment]
@tyrauber 
> EAS_BUILD_DISABLE_COCOAPODS_CACHE, or cache Podfile.lock.

no does not help alpha.14 still the same Error.
alpah.13 no problem.

**Comment by madmeatballs** [comment]
can we reopen this ticket or should we just create a new one?

**Comment by madmeatballs** [comment]
@tyrauber 

if it matters I made a patch which worked without doing the script in XCode manually. Simply reverted the code removed from alpha.14, but modified it to look for XCode 16, I also saw there was `"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";` so I replaced it aswell. This patch works for me.

```
diff --git a/node_modules/@maplibre/maplibre-react-native/android/rctmln/.project b/node_modules/@maplibre/maplibre-react-native/android/rctmln/.project
new file mode 100644
index 0000000..9ab76a1
--- /dev/null
+++ b/node_modules/@maplibre/maplibre-react-native/android/rctmln/.project
@@ -0,0 +1,28 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<projectDescription>
+	<name>maplibre_maplibre-react-native</name>
+	<comment>Project maplibre_maplibre-react-native created by Buildship.</comment>
+	<projects>
+	</projects>
+	<buildSpec>
+		<buildCommand>
+			<name>org.eclipse.buildship.core.gradleprojectbuilder</name>
+			<arguments>
+			</arguments>
+		</buildCommand>
+	</buildSpec>
+	<natures>
+		<nature>org.eclipse.buildship.core.gradleprojectnature</nature>
+	</natures>
+	<filteredResources>
+		<filter>
+			<id>1721909685099</id>
+			<name></name>
+			<type>30</type>
+			<matcher>
+				<id>org.eclipse.core.resources.regexFilterMatcher</id>
+				<arguments>node_modules|\.git|__CREATED_BY_JAVA_LANGUAGE_SERVER__</arguments>
+			</matcher>
+		</filter>
+	</filteredResources>
+</projectDescription>
diff --git a/node_modules/@maplibre/maplibre-react-native/ios/RCTMLN.xcodeproj/project.pbxproj b/node_modules/@maplibre/maplibre-react-native/ios/RCTMLN.xcodeproj/project.pbxproj
index 351b22b..eac2b4b 100644
--- a/node_modules/@maplibre/maplibre-react-native/ios/RCTMLN.xcodeproj/project.pbxproj
+++ b/node_modules/@maplibre/maplibre-react-native/ios/RCTMLN.xcodeproj/project.pbxproj
@@ -706,7 +706,8 @@
 				CLANG_WARN_SUSPICIOUS_MOVE = YES;
 				CLANG_WARN_UNREACHABLE_CODE = YES;
 				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
-				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
+				CODE_SIGN_IDENTITY = "";
+				CODE_SIGNING_REQUIRED = NO;
 				COPY_PHASE_STRIP = NO;
 				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
 				ENABLE_NS_ASSERTIONS = NO;
diff --git a/node_modules/@maplibre/maplibre-react-native/plugin/build/withMapLibre.js b/node_modules/@maplibre/maplibre-react-native/plugin/build/withMapLibre.js
index 37db99a..deb0fda 100644
--- a/node_modules/@maplibre/maplibre-react-native/plugin/build/withMapLibre.js
+++ b/node_modules/@maplibre/maplibre-react-native/plugin/build/withMapLibre.js
@@ -106,6 +106,31 @@ function setExcludedArchitectures(project) {
     }
     return project;
 }
+
+const withoutSignatures = (config) => {
+    const shellScript = `if [ "$XCODE_VERSION_MAJOR" = "1600" ]; then
+      echo "Remove signature files (Xcode 16 workaround)";
+      rm -rf "$CONFIGURATION_BUILD_DIR/MapLibre.xcframework-ios.signature";
+    fi`;
+    return config_plugins_1.withXcodeProject(config, async (config) => {
+      const xcodeProject = config.modResults;
+  
+      xcodeProject.addBuildPhase(
+        [],
+        "PBXShellScriptBuildPhase",
+        "Remove signature files (Xcode 16 workaround)",
+        null,
+        {
+          shellPath: "/bin/sh",
+          shellScript,
+        },
+      );
+  
+      return config;
+    });
+  };
+  
+
 const withExcludedSimulatorArchitectures = (c) => {
     return (0, config_plugins_1.withXcodeProject)(c, (config) => {
         config.modResults = setExcludedArchitectures(config.modResults);
@@ -113,7 +138,7 @@ const withExcludedSimulatorArchitectures = (c) => {
     });
 };
 const withMapLibre = (config) => {
-    config = withExcludedSimulatorArchitectures(config);
+    config = withoutSignatures(withExcludedSimulatorArchitectures(config));
     return withCocoaPodsInstallerBlocks(config);
 };
 exports.default = (0, config_plugins_1.createRunOncePlugin)(withMapLibre, pkg.name, pkg.version);
```

**Comment by tyrauber** [comment]
@madmeatballs, yeah, unfortunately, this would break xCode 15 compatibility.  We could just remove `MapLibre.xcframework-ios.signature` regardless of the xCode version in the expo plugin, but react-native apps would still require manual configuration. 

Disabling the signing of the library so this step isn't required (which alpha.14 should have done), is the optimal solution.  Not sure why this works for some apps, but not others though.

**Comment by tyrauber** [comment]
I took another look at the ios .pbxproj, and realized the alpha.14 fix was only applied to debug builds. My mistake. I made the same change for release builds in 10.0.0-alpha.15.  Please update and report back. If this doesn't work, I'll update the plugin to remove `MapLibre.xcframework-ios.signature` regardless of the Xcode version, but it would be nice if we could have a solution that worked for both expo and react-native.

**Comment by madmeatballs** [comment]
> 2024-09-22 21:48:46.361 xcodebuild[29249:2188179] Writing error result bundle to /var/folders/20/fw8097xd7wz030zfrnkzjr4r0000gn/T/ResultBundle_2024-22-09_21-48-0046.xcresult
xcodebuild: error: “MapLibre.xcframework-ios.signature” couldn’t be copied to “Signatures” because an item with the same name already exists.: The operation couldn’t be completed. File exists

alpha.15 still doesn't work for our workflow @tyrauber

**Comment by tyrauber** [comment]
Ok. Reverted the changes, updated the expo-config plugin to address Xcode 16.   Cut `10.0.0-alpha.17`.  

React Native folks will just need to manual add the [shell script referenced here](https://github.com/maplibre/maplibre-react-native/issues/442#issuecomment-2357829852).  If any xcode wizards know how to prevent a library from generating a .signature file, I would love to hear it!

**Comment by aklevko** [comment]
This problem still exists, xcode: 16.2, @maplibre/maplibre-react-native: "10.1.0"

**Comment by aklevko** [comment]
I resolved that by adding code to "Run Script" section:
- in Xcode select the target you want to modify
- click the Build Phases tab
- choose or create Run Script section
- add code:
`if [ "$XCODE_VERSION_MAJOR" = "1600" ]; then
  echo "Remove signature files (Xcode 16 workaround)"
  find "$BUILD_DIR/${CONFIGURATION}-iphoneos" -name "*.signature" -type f | xargs -r rm
fi
`

**Comment by zayatsRB** [comment]
Just to note: this fix doesn’t work with Xcode 26. Maybe something changed in the new version.

**Comment by tyrauber** [comment]
@zayatsRB, does this not work if you change the version number?

`if [ "$XCODE_VERSION_MAJOR" = "2600" ]; then echo "Remove signature files (Xcode 16 workaround)" find "$BUILD_DIR/${CONFIGURATION}-iphoneos" -name "*.signature" -type f | xargs -r rm fi `

**Comment by cveklica** [comment]
@tyrauber I confirm this script works on Xcode 26.1.1 and with latest V11.0.0-alpha.47

**Comment by sLurPPPeRsTaR** [comment]
> For the ones that can't wait for the release, they can add the following Run Script line in the build phase:
> 
> rm -rf "$CONFIGURATION_BUILD_DIR/MapLibre.xcframework-ios.signature"
> 
> ![Captura de pantalla 2024-09-18 a les 10 26 15](https://github.com/user-attachments/assets/9cc7505d-1941-4add-9f54-cf06d2167cb1)

@lluisandreu thanks a lot bro you save ma day *fist bump*

**Comment by KiwiKilian** [comment]
With the latest v11 releases adding the script manually shouldn't be necessary.
